### ISSUE TITLE
Namespaces are not grouped

### ISSUE THREAD

**Issue by sdressler** [jessevdk/cldoc#103]
When statically generating a site with cldoc 1.8, namespaces are not grouped in the static site. There is no difference between re-using the same namespace in the same file or in different files. For example:

```
namespace foo
{
    class A { };
}

namespace foo
{
    class B { };
}
```

leads to a static site which looks like this:

![screenshot from 2015-07-01 09 03 04](https://cloud.githubusercontent.com/assets/1746936/8449246/09f2ca44-1fd0-11e5-9a42-4fd056cb4aca.png)

As "correct" result, I would have expected that namespaces are grouped.

**Comment by jessevdk** [comment]
Looks like a general problem, even with non-static.

**Comment by jessevdk** [comment]
This was a regression introduced by trying to fix anon structs. This issue should now be resolved, and the fix is included in 1.9 (just released). I've added a test for this specific regression as well. Can you please verify if the latest resolves the issue for you?

**Comment by cbiffle** [comment]
FYI, in my case, this is fixed with latest master.

**Comment by sdressler** [comment]
Yes, I can confirm that this is fixed now.
