### ISSUE TITLE
Issue with C documentation

### ISSUE THREAD

**Issue by hannorein** [jessevdk/cldoc#110]
cldoc is failing to compile the documentation for this test case:

`test.h`:

```
// double a
extern double a;
// double b
extern double b;
```

`test.c`:

```
// double a
double a = 1;
// double b
double b =1;
```

I'm compiling it with cldoc 1.9:

```
cldoc generate  -- --output=doc --language=c  test.c test.h
```

The xml file looks right, but the html file only shows the first variable. Am I missing something or is this a bug?

**Comment by jessevdk** [comment]
I ran this, and both variables show up as expected.
