### ISSUE TITLE
Struct member functions are ignored

### ISSUE THREAD

**Issue by jlaire** [jessevdk/cldoc#112]
Struct member functions don't show up in the documentation, even if they are documented. I tested changing the `struct` keyword to `class` and that solved the issue: the member functions were listed nicely with their comments.

Semantically there is almost no difference between `struct` and `class` in C++, and I think it'd be simplest to handle them identically in the documentation as well. Many programmers use them a bit differently by convention, but I don't think cldoc should be very strict about that. There are multiple distinct uses for structs, such as meta programming and trivial container types, and sometimes a simple struct evolves in to an encapsulated class.

If someone wants to group their structs/classes by category in the documentation, there should be a more generic solution than just grouping by the keyword.

**Comment by jessevdk** [comment]
Seems to work fine for me.
