### ISSUE TITLE
Make it easier to configure documentation generation

### ISSUE THREAD

**Issue by Nicoretti** [jessevdk/cldoc#116]
Generating documentation right now has at least two big drawbacks from my point of view.

1. Specifying Compiler Flags is **tedious** and error prone
2. Specifying a list of files is also **tedious** and error prone 

**Possible solutions for 1.:**
Could be improved by enabling the user to specify one or multiple directories which will be searched and parsed recursively

**Possible solutions for 1 and 2:**
Enable the user to specify a [clang compliation data base file](http://clang.llvm.org/docs/JSONCompilationDatabase.html) which can is also supported by libclang
to determine compilation flags etc. and it also could be used as files to process specification.

BTW Cool Project! (keep up the great work!)

**Comment by jessevdk** [comment]
`cldoc` is not supposed to be used manually, just as you wouldn't normally invoke a c++ compiler manually (apart from trivial samples). It's meant to be integrated in your built system, and it's made such that you can more or less exchange $(CC) by cldoc.

I think supporting a compilation db was brought up before, but I do not see a lot of advantages over just adding a target in either Makefile, automake or cmake. If someone wants to step in and add support for clang compilation db I'd be happy to review and merge it though.

**Comment by jessevdk** [comment]
See https://github.com/jessevdk/cldoc/tree/master/example for samples of `Makefile` and `cmake` integrations.
