### ISSUE TITLE
Not recognizing function parameters and returns

### ISSUE THREAD

**Issue by cdgramos** [jessevdk/cldoc#117]
Hey, cldoc works great but when I'm documenting parameters and return values it simply won't show it as supposed. Instead it show me the parameters and return value as a bullet list.

Example of a function I'm trying to document:

/* io_CheckH Function.
*@h hurst exponent value to be checked.
*
*io_CheckH verifies if a certain given number is in the range of values of the Hurst Exponent.
*@return "ERR" if h < 0.0 || h >= 1.0 otherwise returns "OK".
*/
int io_CheckH (double h);

Documentation generated (a bullet list with this points):
-     @h hurst exponent value to be checked.
-     io_CheckH verifies if a certain given number is in the range of values of the Hurst Exponent.
-     @return "ERR" if h < 0.0 || h >= 1.0 otherwise returns "OK".

I'm doing something wrong? :x

I'm using Ubuntu 14.04. Thanks!

**Comment by jessevdk** [comment]
`cldoc` is strict about format and spacing. Try formatting your comment correctly (see https://github.com/jessevdk/cldoc/blob/master/example/transport/mountainbike.hh#L8 for an example).

**Comment by cdgramos** [comment]
Oh wow. Everything works fine now. 

It was related with the space around the *.

Thanks!!
