### ISSUE TITLE
Clang 3.9 incompatibilities

### ISSUE THREAD

**Issue by wtbarnes** [jessevdk/cldoc#128]
The latest commits to master seem to imply compatibility with clang 3.9 (e.g. [here](https://github.com/jessevdk/cldoc/commit/dd10ac81b0865b7599060c32370c8f171dbd4fba)). 

However, it seems that cldoc checks for v3.4-3.6 only and any other version results in an error (see [this line](https://github.com/jessevdk/cldoc/blob/master/cldoc/tree.py#L53)) as pointed out by #113. If possible, 3.9 should be added to this clang version whitelist.

**Comment by jessevdk** [comment]
More versions have been added now. Could you verify?
