### ISSUE TITLE
Not working with Python3

### ISSUE THREAD

**Issue by mbzeouich** [jessevdk/cldoc#130]
Hello,
Still needs pyparsing 1.5.7 which is not compatible with python3!

**Comment by catskul** [comment]
Pull request here includes upgrade to pyparsing 2.x

https://github.com/jessevdk/cldoc/pull/131

**Comment by PanderMusubi** [comment]
Please merge and release this. I'm also in need of Python 3 implementation. Thanks.

**Comment by jessevdk** [comment]
The PR was not in a state to be merged. I did put some work in trying to make cldoc compatible with python3 (including upgrading pyparsing). Could you see if latest `master` works for you?
