### ISSUE TITLE
Default template parameter values are included in the type signature

### ISSUE THREAD

**Issue by rhdunn** [jessevdk/cldoc#51]
Given:

```
std::list<std::string> foo();
```

The XML output for the return type is:

```
<return>
  <type name="std::list&lt;std::basic_string&lt;char&gt;, std::allocator&lt;std::basic_string&lt;char&gt; &gt; &gt;" qualifier=" const &amp;" />
</return>
```

This is including the allocator argument which is the default version from the template declaration. Thus, the allocator should not be present in the output, which should be:

```
<return>
  <type name="std::list&lt;std::basic_string&lt;char&gt; &gt;" qualifier=" const &amp;" />
</return>
```

With issue #50 fixed, this should be:

```
<return>
  <type name="std::list&lt;std::string&gt;" qualifier=" const &amp;" />
</return>
```

**Comment by jessevdk** [comment]
This has been fixed in latest `master`, but from the looks of it this will only be possible from clang 4.0 or later (3.9 does not expose this information). I'm considering only supporting 4.0 and upwards.
