### ISSUE TITLE
Syntax for commenting out code

### ISSUE THREAD

**Issue by jjrv** [jessevdk/cldoc#56]
If I'm often temporarily adding debug printf's in a file, I might have:

```
//#include <cstdio>

namespace foo {
}
```

However the first line gets parsed as markdown and becomes a gigantic heading documenting the namespace. There should be (or example added mentioning) syntax to comment code out without turning it into documentation.

This is related to #41 and hopefully the syntax for ignoring individual lines would be very simple, like ///.

**Comment by jessevdk** [comment]
Added in documentation.
