### ISSUE TITLE
Grouping methods inside a C++ class

### ISSUE THREAD

**Issue by CorneliusCasa** [jessevdk/cldoc#69]
Categories are a nice feature, but they're not local to a class.

It would be great to be able to group a given class' methods in the doc.

For example, if I have an "Image" class, I may want to group the "width" and "height" methods.

**Comment by jessevdk** [comment]
cldoc doesn't support this by design. See also https://github.com/jessevdk/cldoc/issues/11#issuecomment-14071281.
