### ISSUE TITLE
Full UTF-8 support

### ISSUE THREAD

**Issue by Ricain** [jessevdk/cldoc#78]
Hi,

This characters are not supported: `é`, `è`, `à`, `ç` ...
Could you add them in a way that all French special character will be supported. This is usually done with UTF8.

Right now I have this error:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)
```

It would be really really really helpful if you can add the position, the line and the file name the "unknown" character.

Thank

**Comment by jessevdk** [comment]
cldoc assumes your sources to be in UTF-8. I've just quickly tried a simple thing like:

```c++
/** Ça va */
struct A {};
```

and this works fine for me. Can you provide an example where this doesn't work for you? As for improving the error, this is an exception coming from the python unicode conversion. I'm not sure there is an easy way in which I can improve the error message itself.
