### ISSUE TITLE
not sure how to compile my documentation

### ISSUE THREAD

**Issue by rhl-** [jessevdk/cldoc#81]
I have the following project: http://github.com/appliedtopology/ctl

I added:
add_custom_target(cldoc COMMAND cldoc generate ${CMAKE_CXX_FLAGS} -- --output doc/cldoc ctl/)

to CMakeLists.txt

and:

$ make VERBOSE=1 cldoc
/usr/local/Cellar/cmake/3.1.1_1/bin/cmake -H/Users/rhl/code/ctl -B/Users/rhl/code/ctl --check-build-system CMakeFiles/Makefile.cmake 0
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 cldoc
/usr/local/Cellar/cmake/3.1.1_1/bin/cmake -H/Users/rhl/code/ctl -B/Users/rhl/code/ctl --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.1.1_1/bin/cmake -E cmake_progress_start /Users/rhl/code/ctl/CMakeFiles 0
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/cldoc.dir/all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cldoc.dir/build.make CMakeFiles/cldoc.dir/depend
cd /Users/rhl/code/ctl && /usr/local/Cellar/cmake/3.1.1_1/bin/cmake -E cmake_depends "Unix Makefiles" /Users/rhl/code/ctl /Users/rhl/code/ctl /Users/rhl/code/ctl /Users/rhl/code/ctl /Users/rhl/code/ctl/CMakeFiles/cldoc.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cldoc.dir/build.make CMakeFiles/cldoc.dir/build
cldoc generate -- --output doc/cldoc ctl/
Processing `ctl'
Traceback (most recent call last):
  File "/usr/local/bin/cldoc", line 9, in <module>
    load_entry_point('cldoc==1.6', 'console_scripts', 'cldoc')()
  File "/usr/local/lib/python2.7/site-packages/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/usr/local/lib/python2.7/site-packages/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/usr/local/lib/python2.7/site-packages/cldoc/cmdgenerate.py", line 143, in run
    t.process()
  File "/usr/local/lib/python2.7/site-packages/cldoc/tree.py", line 103, in process
    tu = index.parse(f, self.flags)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 1889, in parse
    self)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 2030, in from_source
    return cls(ptr, index=index)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 2062, in __init__
    ClangObject.__init__(self, ptr)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 1659, in __init__
    assert isinstance(obj, c_object_p) and obj
AssertionError
Exception ctypes.ArgumentError: "argument 1: <type 'exceptions.AttributeError'>: 'TranslationUnit' object has no attribute '_as_parameter_'" in <bound method TranslationUnit.__del__ of <cldoc.clang.cindex.TranslationUnit object at 0x10a607610>> ignored
make[3]: *** [CMakeFiles/cldoc] Error 1
make[2]: *** [CMakeFiles/cldoc.dir/all] Error 2
make[1]: *** [CMakeFiles/cldoc.dir/rule] Error 2
make: *** [cldoc] Error 2

What is going on?

**Comment by jessevdk** [comment]
You have to pass the individual files to be parsed to cldoc, not the directory.

**Comment by rhl-** [comment]
I see. thanks for the response!

Running this: cldoc generate -I. --std=c++11  -- --output doc/cldoc ctl/ctl.h 

where ctl.h is a "catch all" header including all the headers in my header-only generic c++ library

It does generate:

.../doc/cldoc/index.html

but that file is empty.

Do I need to pass it _all_ the header files?

Since they are just headers, i'm not sure what cldoc is doing underneath the hood..

**Comment by rhl-** [comment]
I tried this: 
find ctl/ -name "*.h" | xargs cldoc generate -I. --std=c++11  -- --output doc/cldoc |& fpaste
and I got: http://ur1.ca/jpcm3

**Comment by jessevdk** [comment]
Providing all the headers should work. I've tried this locally with your repo and I get the same issue. It looks like something you do isn't compatible with libc++/c++11 on OS X/clang. I tried skipping that file, but got other errors (looks like some of the headers are missing includes for dependencies, like std::pow).

I don't think these issues have much to do with cldoc.

**Comment by rhl-** [comment]
If you would be so kind as to share exactly what you are doing and what errors your received I would greatly appreciate it. 

I do keep my library compiling on OSX with clang, but, perhaps I am missing something.

**Comment by jessevdk** [comment]
So two things:

1. When I trie to build ctl, I get the following when trying to build the dependencies (`make dependencies`):
```
ar ruv libANN.a ANN.o brute.o kd_tree.o kd_util.o kd_split.o kd_dump.o kd_search.o kd_pr_search.o kd_fix_rad_search.o bd_tree.o bd_search.o bd_pr_search.o bd_fix_rad_search.o perf.o
ar: creating archive libANN.a
a - ANN.o
a - brute.o
a - kd_tree.o
a - kd_util.o
a - kd_split.o
a - kd_dump.o
a - kd_search.o
a - kd_pr_search.o
a - kd_fix_rad_search.o
a - bd_tree.o
a - bd_search.o
a - bd_pr_search.o
a - bd_fix_rad_search.o
a - perf.o
true libANN.a
mv libANN.a ../lib
cd test ; /Applications/Xcode.app/Contents/Developer/usr/bin/make linux-g++
/Applications/Xcode.app/Contents/Developer/usr/bin/make targets \
	"ANNLIB = libANN.a" \
	"C++ = g++" \
	"CFLAGS = -O3" \
	"MAKELIB = ar ruv" \
	"RANLIB = true"
make[9]: *** No rule to make target `../lib/libANN.a', needed by `../bin/ann_test'.  Stop.
make[8]: *** [linux-g++] Error 2
make[7]: *** [linux-g++] Error 2
make[6]: *** [/Users/jesse/devel/ctl/dependencies/ann/src/ann-stamp/ann-build] Error 2
make[5]: *** [CMakeFiles/ann.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [CMakeFiles/ann] Error 2
make[2]: *** [CMakeFiles/ann.dir/all] Error 2
make[1]: *** [CMakeFiles/dependencies.dir/rule] Error 2
make: *** [dependencies] Error 2
```
2. For cldoc specifically, I'm just trying to run `generate` on all the headers. I guess there is something which `libc++` does not really support that well on OS X (related to `tr1`?)

**Comment by rhl-** [comment]
yeah, make dependencies has issues. You can install everything via homebrew though..

**Comment by rhl-** [comment]
also, what
