### ISSUE TITLE
incremental document generation

### ISSUE THREAD

**Issue by fanbin** [jessevdk/cldoc#82]
We tried to adopt cldoc on an existed project (~30k lines), but quickly lost confidence because cldoc kept asking us to correct the comments and make them compatible with cldoc's standards: she refused to generate any result unless we make every-piece-of-comment right. That work might cost us couple of weeks. 

Maybe cldoc could have a 'nice and incremental' mode, in which she just parses those sources files that have compatible comments and ignore those that do not, so that we can gradually make our project compatible with cldoc's comment standard and keep seeing our progress during that process.

**Comment by jessevdk** [comment]
What exactly happens? cldoc should already be graceful in the case of malformed comments, and just report on them.

**Comment by jessevdk** [comment]
No further information has been provided, I'm closing this. Please feel free to reopen if the problem persists.
