### ISSUE TITLE
C function pointer arguments have no documented type.

### ISSUE THREAD

**Issue by jordonbiondo** [jessevdk/cldoc#85]
When I generate documentation for C code like this:

    /* Sort an array of ints using a comparison function
     * @data The array to sort in place
     * @data_length the length of @data
     * @comparator A function used to compare ints, should return -1, 0, or 1 if the first argument is less than, equal to, or greater than the second argument respectively.
     */
    void sort_ints(int* data, int data_length, int(*comparator)(int, int));
    
    void sort_ints(int* data, int data_length, int(*comparator)(int, int)) {
      // do some sorting
    }

The function pointer argument has no documented type, it is only displayed as an untyped pointer in the docs. Preferably the argument would be displayed like this:

    int(*)(int, int) comparator

instead of just:

    *comparator

Here is an image of the currently generated docs:
![screen shot 2015-02-26 at 12 01 17 pm](https://cloud.githubusercontent.com/assets/1441728/6397081/4cad43a0-bdb0-11e4-9af3-e9c4e8a1de34.png)

**Comment by jessevdk** [comment]
I've just pushed support for function pointer types. Could you please try again with the latest master and let me know if this resolved your problems?

**Comment by jessevdk** [comment]
No further information has been provided. I'm closing this. If you still encounter this problem, please feel free to reopen the issue.
