### ISSUE TITLE
Cannot build cldoc locally, likely due to breaking changes in dependencies.

### ISSUE THREAD

**Issue by jordonbiondo** [jessevdk/cldoc#86]
While trying to fix https://github.com/jessevdk/cldoc/issues/85, I found that I cannot build cldoc locally.

Before going into all the specific errors and possible solutions, I think they can all likely be fixed if I had the correct versions installed of tall the dependencies since versions are not specified and I likely have newer, incompatible versions being installed.

So what versions of the following are actually required?

- node
- sass
- inliner
- coffee
- python

My installed versions are:

- node: 0.11.14
- inliner: 0.1.16
- coffee: 1.9.1
- sass: 3.4.13
- python: 2.7.6

**Comment by jessevdk** [comment]
Can you please paste the error, it will be easier to identify if a newer version is causing issues. In general cldoc should be updated to support newer versions.

**Comment by jessevdk** [comment]
I have pinned the versions of coffee and inline-source. I don't have any issues myself, and no further information has been provided. Please feel free to reopen this issue if you still encounter problems.

**Comment by jordonbiondo** [comment]
Thanks I'll see if I can't try out a fresh pull and build if I get some time soon.
