### ISSUE TITLE
OSX 10.9.5 - cldoc.clang.cindex.LibclangError: dlopen(libclang.dylib, 6): image not found.

### ISSUE THREAD

**Issue by ibc** [jessevdk/cldoc#87]
Should cldoc run on OSX? I've installed it via `pip` but it seems that it does not find the libclang.dylib library which is located at `./Library/Developer/CommandLineTools/usr/lib/libclang.dylib`.

How to make it work? I do not see any option to tell `cldoc` where to find such a library.

**Comment by ibc** [comment]
Creating a symlink to the above path form`/usr/local/lib` does work...

**Comment by jessevdk** [comment]
Should be fixed, I've added that path to the search paths.

**Comment by ibc** [comment]
:+1:
