### ISSUE TITLE
Unable to locate libclang.dylib MacOSX Yosemite

### ISSUE THREAD

**Issue by lzuwei** [jessevdk/cldoc#88]
I am having some issues on MacOSX Yosemite, 
cldoc is complaining about libclang.dylib

it is located in /Library/Developer/CommandLineTools/usr/lib/libclang.dylib on my machine.
Is there an easy way to point to this?

cldoc.clang.cindex.LibclangError: dlopen(libclang.dylib, 6): image not found. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().

**Comment by jessevdk** [comment]
On OS X we look at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib. This works for me on Yosemite, but obviously you'll need Xcode installed. I'm on Yosemite and I don't have /Library/Developer/CommandLineTools/usr/lib/libclang.dylib.

For now this path is hard-coded at: https://github.com/jessevdk/cldoc/blob/master/cldoc/tree.py#L33. As a quick hack you can try modifying that and see if it resolves your issue. I'm not yet sure what the correct fix is for cldoc itself though.

**Comment by jessevdk** [comment]
Should be fixed in #87.
