### ISSUE TITLE
actual error with cldoc on osx 

### ISSUE THREAD

**Issue by rhl-** [jessevdk/cldoc#89]
$ cat test.hpp 
#include \<vector\>
/**
* @struct Foo
* @brief Foobar
*/
struct Foo{}; //end class

$ cldoc generate -- --output=test test.hpp 
Processing `test.hpp'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:153:8: error: no member named 'int8_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:154:8: error: no member named 'int16_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:155:8: error: no member named 'int32_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:156:8: error: no member named 'int64_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:158:8: error: no member named 'uint8_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:159:8: error: no member named 'uint16_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:160:8: error: no member named 'uint32_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:161:8: error: no member named 'uint64_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:163:8: error: no member named 'int_least8_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:164:8: error: no member named 'int_least16_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:165:8: error: no member named 'int_least32_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:166:8: error: no member named 'int_least64_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:168:8: error: no member named 'uint_least8_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:169:8: error: no member named 'uint_least16_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:170:8: error: no member named 'uint_least32_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:171:8: error: no member named 'uint_least64_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:173:8: error: no member named 'int_fast8_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:174:8: error: no member named 'int_fast16_t' in the global namespace
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdint:175:8: error: no member named 'int_fast32_t' in the global namespace
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Removing the #include< vector> I get beautiful documentation!

**Comment by rhl-** [comment]
For what it is worth I also see a perhaps different(?) issue with this code on my Fedora 20 system: 

$ cldoc generate -- --output=test ./test.hpp 
Traceback (most recent call last):
  File "/usr/bin/cldoc", line 9, in <module>
    load_entry_point('cldoc==1.7', 'console_scripts', 'cldoc')()
  File "/usr/lib/python2.7/site-packages/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/usr/lib/python2.7/site-packages/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/usr/lib/python2.7/site-packages/cldoc/cmdgenerate.py", line 142, in run
    t = tree.Tree(opts.files, cxxflags)
  File "/usr/lib/python2.7/site-packages/cldoc/tree.py", line 61, in __init__
    self.flags = includepaths.flags(flags)
  File "/usr/lib/python2.7/site-packages/cldoc/includepaths.py", line 21, in flags
    stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I'm wondering if `pip install cldoc` is working correctly? is there some kind of a `make test?`

**Comment by jessevdk** [comment]
1. This exact sample works fine for me. Looks like a possible issue in your environment in general?
1. cldoc will execute clang++ to try and find out the system include headers. This is needed because for some reason libclang won't by default include these when searching for headers (while parsing). Looks like you don't have clang++ installed. Newer versions of cldoc should give you a better error message.

**Comment by rhl-** [comment]
How did you install clang++ ?
$ clang++
clang: error: no input files
$ clang++ --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

Upgrading cldoc I now get:
Traceback (most recent call last):
  File "/usr/local/bin/cldoc", line 9, in <module>
    load_entry_point('cldoc==1.7', 'console_scripts', 'cldoc')()
  File "/usr/local/lib/python2.7/site-packages/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/usr/local/lib/python2.7/site-packages/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/usr/local/lib/python2.7/site-packages/cldoc/cmdgenerate.py", line 144, in run
    t.process()
  File "/usr/local/lib/python2.7/site-packages/cldoc/tree.py", line 115, in process
    self.index = cindex.Index.create()
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 2096, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 153, in __get__
    value = self.wrapped(instance)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 3430, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 3377, in register_functions
    map(register, functionList)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 3375, in register
    return register_function(lib, item, ignore_errors)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 3356, in register_function
    raise LibclangError(msg)
cldoc.clang.cindex.LibclangError: dlsym(0x7f8d83011c80, clang_CXXMethod_isPureVirtual): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.

**Comment by rhl-** [comment]
It looks like you have bundled some libclang source in your package, which is dependent on version 3.4. OS/X Yosemite ships with a newer version of libclang.so which causes that error.

I think you are right about the headers from earlier, but, unless you can explain otherwise, I think that is a bug in your inclusion of headers, since I clearly have clang++ installed...

**Comment by rhl-** [comment]
Note, OS/X Yosemite update just pushed my clang version to 3.6 where this issue still exists.

**Comment by jessevdk** [comment]
I'm running OS/X Yosemite with clang 3.6svn, and I don't have this problem. So it isn't as simple as you propose. The python bindings that we ship are from 3.3, so should be compatible with any version >= 3.3. If it can't find clang_CXXMethod_isPureVirtual, then it must somehow pick up a libclang <= 3.2.

cldoc tries to locate libclang on OS X at the following locations:

- /Library/Developer/CommandLineTools/usr/lib/libclang.dylib
- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib

Could it be you have some older version of clang installed in the first of these paths?

**Comment by rhl-** [comment]
$ find / -name "libclang.dylib" 2> /dev/null 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
/Library/Developer/CommandLineTools/usr/lib/libclang.dylib

$ md5 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
MD5 (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib) = 112767ea69a9c1426ffef8e27b89fa2d

md5 /Library/Developer/CommandLineTools/usr/lib/libclang.dylib
MD5 (/Library/Developer/CommandLineTools/usr/lib/libclang.dylib) = 112767ea69a9c1426ffef8e27b89fa2d

$ sudo rm -rf CommandLineTools/
(I also uninstalled XCode)

$ xcode-select --install
$ md5 /Library/Developer/CommandLineTools/usr/lib/libclang.dylib
MD5 (/Library/Developer/CommandLineTools/usr/lib/libclang.dylib) = 112767ea69a9c1426ffef8e27b89fa2d

Xcode is currently reinstalling, but, it looks like those versions are up to date with whatever is out there..

Can you confirm that you have the same hashes?

**Comment by jessevdk** [comment]
Yep, same here: 112767ea69a9c1426ffef8e27b89fa2d

**Comment by Ventero** [comment]
I was able to reproduce the issue from the original report on my system (OS X 10.9.5 with clang installed via `xcode-select --install`), but was able to fix it by switching around the search order of the two paths for libclang.dylib in tree.py.

**Comment by rhl-** [comment]
confirmed after switching that order I get:

$ cldoc generate -- --output=test test.hpp 
Processing test.hpp
Generated `test/xml'
Generated `test/index.html'

**Comment by rhl-** [comment]
I find it odd since the md5 hash of each of those dylibs is the same.

**Comment by jessevdk** [comment]
I guess they could be relatively linking to different llvm's.
