### ISSUE TITLE
Empty page with Clang 3.6 on Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by kirbyfan64** [jessevdk/cldoc#90]
```
ryan@DevPC-LX:~/stuff/cldoc/example$ make doc
Generating documentation...
Processing bicycle.cc
Processing mountainbike.cc
Unhandled cursor: CursorKind.COMPOUND_STMT
Processing racingbike.cc
Processing transport.hh
Generated `html/xml'
Generated `html/index.html'
ryan@DevPC-LX:~/stuff/cldoc/example$ 
```

When I open up the generated HTML, it's empty. All I see are the two panes. No text.

**Comment by lzuwei** [comment]
I am encountering the same problem as well on Mac OSX clang 3.6

**Comment by jessevdk** [comment]
Just tried with clang 3.6 on OS X (clang+llvm-3.6.0-x86_64-apple-darwin) and I can't reproduce the issue. Could you please:

1. Send me the generated files (if you can)
1. Look at the web console when you open the page and see if there are any errors

**Comment by kirbyfan64** [comment]
Figured out the issue:

```
XMLHttpRequest cannot load file:///media/ryan/stuff/cldoc/example/html/xml/index.xml?_=1428945463031. Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, https, chrome-extension-resource.
```

I pulled up `python -m SimpleHTTPServer` and it worked. Looks like a Chrome thing. Closing.

**Comment by jessevdk** [comment]
Yes, you can run "cldoc serve" to do the same. The dynamic site can't be
run directly from disk, but you can use the --static open of "generate" to
generate a site that you can serve completely statically.

2015-04-13 19:18 GMT+02:00 Ryan Gonzalez <notifications@github.com>:

**Comment by kirbyfan64** [comment]
@jessevdk I didn't know about that...thanks!
