### ISSUE TITLE
pip install --user fails

### ISSUE THREAD

**Issue by gvol** [jessevdk/cldoc#93]
I thought you might like to know that installing with --user failed on OS X 10.10.3.  I have home brew installed etc.  I installed globally with no problems.

    $ pip install --user cldoc
    Collecting cldoc
      Downloading cldoc-1.7.tar.gz (243kB)
        100% |################################| 245kB 4.2MB/s
    Requirement already satisfied (use --upgrade to upgrade): pyparsing==1.5.7 in /Users/iandrus/Library/Python/2.7/lib/python/site-packages (from cldoc)
    Installing collected packages: cldoc
      Running setup.py install for cldoc
        error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
        Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/var/folders/d3/yxwv5yn5715fk31lq36lnk780000gn/T/pip-build-gvpbzp/cldoc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/d3/yxwv5yn5715fk31lq36lnk780000gn/T/pip-HIpuiW-record/install-record.txt --single-version-externally-managed --compile --user:
        running install

        error: can't combine user with prefix, exec_prefix/home, or install_(plat)base

        ----------------------------------------
        Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/var/folders/d3/yxwv5yn5715fk31lq36lnk780000gn/T/pip-build-gvpbzp/cldoc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/d3/yxwv5yn5715fk31lq36lnk780000gn/T/pip-HIpuiW-record/install-record.txt --single-version-externally-managed --compile --user" failed with error code 1 in /var/folders/d3/yxwv5yn5715fk31lq36lnk780000gn/T/pip-build-gvpbzp/cldoc
    
    $ uname -a 
    Darwin iandrus-osx 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by jessevdk** [comment]
This looks like a problem of your pip installation? I must confess, I'm not too familiar with setuptools/pip etc. Maybe it's something related to this:

http://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install

**Comment by jessevdk** [comment]
No further information has been provided, closing this. If you still have issues, please feel free to reopen this issue.

**Comment by proski** [comment]
It's a well-known homebrew limitation. In a misguided attempt to prevent a conflict with the system Python, homebrew effectively disabled --user for its own version of Python. The only solution is to tell the homebrew team to think harder and find a solution that doesn't break for the users.
