### ISSUE TITLE
Incorrect handling of typedefs which are templates of another typedef

### ISSUE THREAD

**Issue by Ventero** [jessevdk/cldoc#95]
When generating the documentation of the file shown below, `v8` is incorrectly shown as typedef for `u8` instead of `std::vector<u8>` or `std::vector<unsigned char>`.

```c++
#include <vector>

typedef unsigned char u8;
typedef std::vector<u8> v8;
```

**Comment by jessevdk** [comment]
This is related to #50. Unfortunately, libclang doesn't seem to expose these things correctly, so we don't really have enough information to extract this.

**Comment by Ventero** [comment]
Sure, it might not be possible to get the exact definition as `std::vector<u8>`, but at least correctly documenting the underlying type should be possible, right?

When I comment out `Typedef#visit` in `cldoc/nodes/typedef.py`, `v8` is correctly documented as `std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >` - which, while not pretty, is at least correct.

**Comment by jessevdk** [comment]
Yes, you're absolutely right. That visit is done to try and deduce the type and format it nicer. This is obviously not correct for your case. I'll push a fix shortly.
