### ISSUE TITLE
unhandled things?

### ISSUE THREAD

**Issue by rhl-** [jessevdk/cldoc#96]
What does this mean: 

`Unhandled cursor: CursorKind.NAMESPACE_REF`

`Unhandled cursor: CursorKind.COMPOUND_STMT`

`Unhandled cursor: CursorKind.MEMBER_REF`

`Unhandled cursor: CursorKind.UNEXPOSED_EXPR`

Here are all of them: http://paste.fedoraproject.org/213626/29580308

Are these normal? errors? They have no context... Can they be logged to a separate file?

**Comment by jessevdk** [comment]
These are indicators of unsupported cursor types, i.e. cursors that we don't handle at all and just ignore. This has been a good indicator of missing support for certain features and helps when people report issues. I agree though that they can go behind a flag, --verbose, or something similar.
