### ISSUE TITLE
markdown?

### ISSUE THREAD

**Issue by rhl-** [jessevdk/cldoc#97]
I wrote two markdown files similar to the tutorial and ran:

`$ cldoc generate -std=c++11 -I/Users/rhl/code/ctl -- --output=./doc --merge=./doc/markdown $(cat header_file_names) `

But the markdown doesn't "just appear" when I type 'cldoc serve' its not clear to me what I am doing wrong. There appears to be no errors..

**Comment by jessevdk** [comment]
Please paste the markdown.

**Comment by rhl-** [comment]
#<cldoc:index>
CTL: The Computational Topology Library

# Documentation

This page lists the complete functionality of [CTL](http://ctl.appliedtopology.org). 
It is compiled automatically from the source code.
$ cat ctl.md 
#<cldoc:ctl>

The entire library lives within the CTL namespace.

**Comment by jessevdk** [comment]
As a test, I update the example/docs/index.md with your pasted index.md and example/docs/transport.md with your ctl.md. Run the doc generation, this works. The merged in markdown shows up as expected. Does any merged doc show up in the generated xml/index.xml ?

**Comment by rhl-** [comment]
Hm weird. This time, duplicating this, it works..
